version: "3.9"

volumes:
  perlite: {}

services:
  perlite:
    image: haruvon/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=notes
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
    ports:
      - 9005:80
    volumes:
      - ./perlite/Demo:/var/www/perlite/notes:ro
      - perlite:/var/www/perlite:ro
