version: "3.9"

services:
  perlite:
    image: perlite-dev:latest
    container_name: perlite-dev
    environment:
      - NOTES_PATH=notes
      - LINE_BREAKS=true
      - HIDE_FOLDERS=docs,private,trash
    ports:
      - 80:80
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/notes:ro
